version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: order-postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - order-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: order-pgadmin
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - order-network

  api:
    build: .
    container_name: order-api
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      - postgres
    networks:
      - order-network

networks:
  order-network:

volumes:
  postgres_data: